declare module 'react-native-ico-coolicons' {
    import { ReactNode } from 'react';
    import { SvgProps } from 'react-native-svg';

    type AdditionalProps = {
      onError?: (error: Error) => void;
      onLoad?: () => void;
      fallback?: ReactNode;
    };

    type iconNames = 'jar-black-shape' |
      'wireless-signal-interface-status-symbol-of-bars-group' |
      'plus-sign-in-a-square-symbol-of-gross-line' |
      'connection-interface-symbol-of-three-circles-with-lines-unions' |
      'folder-gross-symbol-for-interface' |
      'minus-sign-in-a-square-1' |
      'numbered-list' |
      'currency-symbol' |
      'film-strip-of-cinema-symbol' |
      'linked-in-logo-of-two-letters' |
      'left-arrow' |
      'moon-shape' |
      'giftbox-black-variant-with-a-ribbon-on-top' |
      'square-outline' |
      'angle-arrow-pointing-down' |
      'sort-numerically-down-interface-symbol' |
      'calendar' |
      'shield-shape-outline' |
      'hand-black-shape-pointing-left-with-one-finger' |
      'two-black-paper-sheets-symbol' |
      'hotel-letter-sign' |
      'rails' |
      'film-clapperboard' |
      'sign-of-lines' |
      'alphabetical-order-from-a-to-z' |
      'font-interface-symbol' |
      'download-from-internet-interface-symbol' |
      'presentation-screen-tool-outline-symbol' |
      'subscript-interface-option-symbol' |
      'html-5-logotype' |
      'crop-interface-symbol' |
      'double-left-arrows-angles' |
      'dollar-symbol' |
      'compass-tool-1' |
      'exclamation-sign' |
      'two-straight-arrows' |
      'marker-outline' |
      'speaker-black-tool-shape-interface-symbol' |
      'menu-interface-symbol-of-three-horizontal-straight-lines' |
      'youtube-rounded-square-logo' |
      'hand-finger-pointing-down-like-an-arrow' |
      'suitcase-black-shape-1' |
      'two-arrows-in-angle-pointing-down' |
      'information-sign' |
      'musical-disc' |
      'label-black-shape' |
      'vk-logo-of-social-network' |
      'leaves-on-a-branch-silhouette' |
      'video-camera' |
      'shopping-cart-black-silhouette-rounded-variant' |
      'right-arrow-symbol' |
      'image-interface-symbol-of-a-landscape' |
      'two-opposite-arrows' |
      'md' |
      'up-arrow-angle' |
      'advance-button' |
      'text-option-interface-symbol' |
      'right-arrow-for-forward-button-gross-symbol' |
      'fast-forward' |
      'female-silhouette' |
      'wedding-rings-couple' |
      'birthday-cake-of-three-cakes' |
      'twitter-bird-logo-shape-in-a-square' |
      'up-arrow-angle-1' |
      'triangular-up-arrow' |
      'three-black-squares' |
      'black-rounded-square-shape' |
      'lightning-bolt-black-shape' |
      'code-interface-symbol-of-signs' |
      'arrow-long-angle-pointing-right' |
      'building-shape' |
      'commercial-label-black-shape' |
      'broken-link-interface-symbol-of-chain-links-with-a-slash' |
      'view-eye-interface-symbol' |
      'left-arrow-variant' |
      'coffee-hot-black-cup-of-rounded-shapes' |
      'new-email-black-back-envelope-symbol-of-interface' |
      'text-option-interface-symbol-1' |
      'right-arrow-angle-of-two-shapes' |
      'suitcase-black-shape' |
      'linux-penguin' |
      'square-outline-with-up-arrow' |
      'box-from-side-view' |
      'left-arrow-in-rounded-shape' |
      'black-square-shape' |
      'network-or-hierarchy-graphic' |
      'question-mark-in-circular-shape' |
      'leaf-shape' |
      'four-squares-black-shapes' |
      'speaker-interface-audio-symbol' |
      'facebook-letter-logo' |
      'three-rectangles-symbol' |
      'bitcoin-symbol' |
      'cloud-black-shape' |
      'up-arrow-in-a-circle' |
      'close-cross-sign-in-a-square-button' |
      'pencil-black-tool-interface-symbol' |
      'minus-straight-horizontal-line-sign' |
      'verification-sign-in-a-circle' |
      'plus-zoom-interface-symbol' |
      'eye-opened-shape-with-signal-connection-lines' |
      'sort-by-reverse-alphabet-order-interface-symbol' |
      'ruble-currency-sign' |
      'minus-sign' |
      'google-plus-logo' |
      'key-shape' |
      'up-arrow-triangle-in-a-square-gross-outline' |
      'microphone-with-slash-interface-symbol-for-mute-audio' |
      'ambulance' |
      'bitbucket-logo-1' |
      'instagram-photo-camera-symbol' |
      'star-gross-outline' |
      'less-zoom-sign' |
      'xing-logo-1' |
      'order-interface-symbol-with-down-arrow' |
      'logo-of-striped-rounded-square-speech-bubble-shape' |
      'star-on-vip-card' |
      'exclamation-sign-in-a-rhomb' |
      'play-triangular-button-symbol-in-a-circle' |
      'heart-in-a-circle' |
      'star-shape-symbol-with-half-black-and-half-white' |
      'wheel-shape-variant' |
      'download-arrow' |
      'three-aligned-squares-in-vertical-line-interface-button' |
      'up-and-down-arrows' |
      'right-arrow-in-a-circle-1' |
      'arrow-pointing-upper-right-in-a-square' |
      'file-gross-interface-symbol' |
      'up-long-arrow' |
      'up-arrows-angles-couple' |
      'unlocked-padlock' |
      'legal-hammer' |
      'underline-text-option-interface-symbol' |
      'xing-logo' |
      'thumb-down-symbol' |
      'camping-tent' |
      'credit-card-back-view' |
      'sad-emoticon-face' |
      'down-black-arrow' |
      'question-sign' |
      'github-logo-silhouette-in-a-square' |
      'small-truck-black-side-view-silhouette' |
      'camping' |
      'left-arrow-angle' |
      'fire-with-logs-cross' |
      'sort-interface-symbol-of-down-arrow-with-numbers' |
      'daily-calendar-empty-page' |
      'discapacity-wheels-chair-circular-sign' |
      'paperclip-spiral' |
      'up-and-down-small-triangular-arrows' |
      'up-arrow-in-a-circle-1' |
      'man-standing-black-silhouette' |
      'bars-interface-symbol' |
      'android-logo-1' |
      'check-mark-sign' |
      'music-discs' |
      'cross-sign' |
      'power-symbol' |
      'placeholders' |
      'four-circles-black-group' |
      'heart-outline-shape' |
      'text-alignment-to-right' |
      'monitor' |
      'opposite-arrows-couple' |
      'back' |
      'windows-logo' |
      'half-black-star-shape' |
      'bell-black-tool-shape' |
      'down-arrow-black-triangular-variant-symbol' |
      'cardinal-points-star-of-a-circle-with-four-triangles' |
      'plus-sign-in-a-square' |
      'wireless-keyboard' |
      'two-arrows' |
      'strikethrough-text-option-interface-symbol-1' |
      'photo-camera-of-square-shape' |
      'id-card-interface-rectangular-symbol' |
      'train-travelling-on-railroad' |
      'right-arrow-angle-inside-a-square' |
      'tumblr-letter-logo' |
      'glass-black-shape-for-wine' |
      'menu-interface-symbol-of-four-horizontal-lines-with-dots' |
      'left-arrow-in-a-circle' |
      'black-folder-interface-symbol' |
      'clapper-for-cinema-filming' |
      'orientation-winds-star-pointing-cardinal-points' |
      'left-and-right-small-triangular-arrows-couple' |
      'upper-right-arrow-black-symbol' |
      'recycle-bin' |
      'letter-b-symbol' |
      'sort-descending-interface-down-arrow-symbol-with-horizontal-text-lines' |
      'left-arrow-2' |
      'flask-glass-container-with-liquid-inside' |
      'user-image-on-phone-screen-in-horizontal-position' |
      'list-1' |
      'diamond-ring-shape' |
      'airplane-black-shape' |
      'control-of-rectangular-shape' |
      'flag-of-rectangle-outline-on-a-pole' |
      'left-arrow-black-triangular-shape' |
      'drop-shape' |
      'rectangles-symbol' |
      'clipboard-and-paper-sheet' |
      'overflowing-stacked-papers-tray' |
      'bitbucket-logo' |
      'fire-gross-flame-black-symbol' |
      'backward-arrows-couple' |
      'home-black-shape' |
      'circular-stairs-from-top-view' |
      'message-black-speech-bubble-of-rectangular-shape' |
      'locked-padlock-security-interface-symbol' |
      'like-symbol-for-interface-of-black-hand-shape-with-thumb-up' |
      'book-gross-black-shape' |
      'speaker' |
      'fire-extinguisher-black-tool-shape' |
      'wrench-black-silhouette-of-tool' |
      'rewind-button' |
      'war-airplane-bottom-view-black-shape' |
      'restaurant-interface-symbol-of-fork-and-knife-couple' |
      'arrows-shuffle-symbol' |
      'rss-feed-suscription-button-symbol-for-interface' |
      'right-arrow-black-triangle-1' |
      'up-level-arrow' |
      'circle-outline-with-a-central-dot' |
      'down-arrow-in-a-circle-2' |
      'black-hand-finger-pointing-up' |
      'hard-disc' |
      'hide-interface-symbol' |
      'google-plus-square-logo' |
      'left-arrow-square' |
      'flag-black-tool-shape' |
      'sign' |
      'arrow-angle-pointing-to-right' |
      'skype-logo' |
      'up-arrow-inside-a-gross-circle' |
      'lemon-shape' |
      'file-interface-symbol' |
      'tablet-tool-variant' |
      'descendant-arrow-angle' |
      'up-triangular-arrow' |
      'megaphone-silhouette' |
      'magic-wand' |
      'table-tennis-racquet-or-rattle-musical-instrument-black-silhouette-shape' |
      'right-arrow-angle-and-horizontal-down-line-code-signs' |
      'pinterest-letter-logo-in-a-square' |
      'yen-symbol' |
      'microphone-voice-interface-symbol' |
      'square-with-two-rectangles-inside' |
      'medical-tool-to-listen-heart-beats' |
      'youtube-logo' |
      'checkered-flag-on-a-pole' |
      'letter-a-sign-in-a-circle' |
      'strikethrough-text-option-interface-symbol' |
      'minus-sign-in-a-square' |
      'superscript-symbol' |
      'baby-cradle-silhouette' |
      'apple-black-shape-logo-with-a-bite-hole' |
      'first-aid-kit-box-with-cross-sign' |
      'circular-arrow' |
      'circular-arrow-line' |
      'github-logo-face' |
      'dollar-bill' |
      'weekly-calendar-variant' |
      'center-alignment-symbol' |
      'italic-text-option-interface-symbol' |
      'accept-1' |
      'ice-cream-cone-black-shape' |
      'down-arrow-1' |
      'puzzle-piece-black-shape-of-border' |
      'dice-on-three-face' |
      'speedometer' |
      'renren-china-social-network-logo' |
      'trophy-black-side-view-silhouette' |
      'black-back-closed-envelope-shape' |
      'up-arrow-triangle' |
      'rounded-square-corners-outline' |
      'funnel-black-shape-interface-symbol' |
      'circle-shape' |
      'left-quotes-sign' |
      'right-arrow-direction' |
      'accept' |
      'tray-interface-symbol' |
      'three-gears-interface-symbol-for-settings' |
      'flickr-logo-variant-of-two-dots-in-a-rounded-square' |
      'pause' |
      'list-interface-symbol' |
      'magnet' |
      'dropbox-logo' |
      'square-outline-shape' |
      'twitter-letter-logo-symbol-in-a-square' |
      'folder-black-shape' |
      'triangular-black-arrow-pointing-down' |
      'tag-black-tool-shape' |
      'phone-keys-black-nine-squares' |
      'up-arrow-in-circular-shape' |
      'star-black-shape-favourite-interface-symbol' |
      'folder-gross-outline-shape-interface-symbol' |
      'photo-camera-interface-symbol-1' |
      'prohibition-symbol-of-a-circle-with-a-slash' |
      'android-logo' |
      'thumb-up-gross-line-symbol' |
      'audio-tool-for-head' |
      'right-arrow-black-shape' |
      'player-play-button-of-circular-shape' |
      'world-ball' |
      'clock-circular-outline' |
      'text-height-format-interface-option-symbol' |
      'dislike-hand-symbol' |
      'text-side-option-interface-symbol' |
      'html-3-logo' |
      'padlock-locked-black-shape' |
      'three-squares-line' |
      'basketball-ball-outline' |
      'hotel-building' |
      'placeholder-interface-symbol-for-maps' |
      'musical-note-black-shape' |
      'delete-cross-interface-symbol' |
      'link-interface-symbol' |
      'bell-outline' |
      'interface-upload-up-arrow-symbol' |
      'floppy-disk-interface-symbol-for-save-option-button' |
      'down-arrow-triangle-in-a-square-of-gross-line' |
      'circular-arrows-couple' |
      'plus-sign-1' |
      'contrast-interface-circular-symbol-half-black-half-white' |
      'music-disc' |
      'left-arrow-in-a-circle-1' |
      'right-quotes-symbol' |
      'fast-forward-multimedia-control-arrows' |
      'space-ship' |
      'pin-black-tool-shape' |
      'two-columns-layout' |
      'edit-interface-symbol-of-square-paper-with-a-pencil' |
      'euro-currency-sign' |
      'vimeo-letter-logo-in-a-square' |
      'flower-with-ribbon-tails' |
      'targeting' |
      'phone-shape' |
      'photo-camera-interface-symbol' |
      'plus-sign' |
      'status-interface-symbol' |
      'right-arrow-angle' |
      'group-interface-symbol' |
      'anchor-interface-symbol' |
      'play-square-button' |
      'exclamation-sign-1' |
      'speech-bubble-couple-of-black-rectangular-shapes' |
      'sun-black-shape' |
      'placeholder' |
      'info-letter-interface-sign' |
      'linkedin-square-logo' |
      'hand-finger-pointing-to-right-direction-like-an-arrow' |
      'verification-symbol-in-a-square-box' |
      'twitter-black-shape' |
      'right-arrow-black-triangle' |
      'verification-symbol' |
      'barcode-square-variant' |
      'maxcdn-letter-logo' |
      'print-interface-symbol' |
      'left-arrow-1' |
      'target-concentric-circles-symbol' |
      'four-horizontal-lines-interface-symbol' |
      'umbrella-black-shape' |
      'lightbulb-gross-outline' |
      'heart-black-shape' |
      'up-arrow' |
      'file-gross-outline-interface-symbol' |
      'down-arrow-in-a-circle' |
      'pinterest-circular-logo-symbol' |
      'qr-code-variant' |
      'rss-feeds-symbol-in-a-rounded-square' |
      'level-down-arrow' |
      'down-arrow-in-a-circle-1' |
      'left-arrow-angle-variant' |
      'serious-emoticon-face' |
      'right-arrow-in-a-circle' |
      'down-arrow' |
      'pencil-in-a-square-interface-symbol-of-gross-outline' |
      'call-symbol-of-an-auricular-in-a-square' |
      'golf-flag-and-field' |
      'rectangular-speech-bubble-of-chat' |
      'verify' |
      'right-external-arrow-of-a-square' |
      'compass-tool' |
      'player-play-button-symbol' |
      'left-text-alignment-interface-option' |
      'facebook-logo' |
      'paw-black-shape' |
      'bug-variant-of-circular-shape-with-spots' |
      'speech-bubbles-interface-chat-symbol' |
      'asterisk-black-star-shape' |
      'right-long-black-arrow' |
      'smiling-face' |
      'bookmark-black-shape' |
      'unlocked-padlock-symbol' |
      'file-black-paper-sheet-interface-symbol' |
      'list' |
      'upload-to-the-cloud-interface-symbol' |
      'user-black-shape' |
      'laptop-with-empty-screen' |
      'call-black-auricular-shape';

    type iconColors = ;

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors?: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
